// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdM4-i9FOimF14O_IEfX8F0AQeiyG-8Hs',
    appId: '1:690385838703:web:af2b763c560bc142b6a39a',
    messagingSenderId: '690385838703',
    projectId: 'boardapp-d9860',
    authDomain: 'boardapp-d9860.firebaseapp.com',
    storageBucket: 'boardapp-d9860.firebasestorage.app',
    measurementId: 'G-LPLKP64STF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa_jG-Qx1vTcJU1c5HXiu--kTE1aR5fIk',
    appId: '1:690385838703:android:9fa3346630d911a6b6a39a',
    messagingSenderId: '690385838703',
    projectId: 'boardapp-d9860',
    storageBucket: 'boardapp-d9860.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDnTwS2GThedmMVsYPy6TVyOAirfxcYUw',
    appId: '1:690385838703:ios:df4eebf38839d482b6a39a',
    messagingSenderId: '690385838703',
    projectId: 'boardapp-d9860',
    storageBucket: 'boardapp-d9860.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardAppHw04',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDnTwS2GThedmMVsYPy6TVyOAirfxcYUw',
    appId: '1:690385838703:ios:df4eebf38839d482b6a39a',
    messagingSenderId: '690385838703',
    projectId: 'boardapp-d9860',
    storageBucket: 'boardapp-d9860.firebasestorage.app',
    iosBundleId: 'com.example.messageBoardAppHw04',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAdM4-i9FOimF14O_IEfX8F0AQeiyG-8Hs',
    appId: '1:690385838703:web:905dc0f443aa3b01b6a39a',
    messagingSenderId: '690385838703',
    projectId: 'boardapp-d9860',
    authDomain: 'boardapp-d9860.firebaseapp.com',
    storageBucket: 'boardapp-d9860.firebasestorage.app',
    measurementId: 'G-X9FEYNZXDN',
  );
}
